### ISSUE TITLE
Update content for Observables & RxJS to Angular 7 and RxJS 6

### ISSUE THREAD

**Issue by jawache** [codecraft-tv/angular-course#4]
The content references https://cdnjs.cloudflare.com/ajax/libs/rxjs/4.1.0/rx.all.js instead of Angular project in the example

The content doesn't use the pipe operator

**Comment by jawache** [comment]
This is the section 

https://codecraft.tv/courses/angular/reactive-programming-with-rxjs/observables-and-rxjs/

**Comment by jawache** [comment]
https://youtu.be/BhXSsR_y76I

**Comment by jawache** [comment]
@priyath

**Comment by priyath** [comment]
@jawache PR for the changes: https://github.com/codecraft-tv/angular-course/pull/37
